// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WmBlazor.Server.Data;

#nullable disable

namespace WmBlazor.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GameTag", b =>
                {
                    b.Property<int>("GamesId")
                        .HasColumnType("int");

                    b.Property<int>("TagsId")
                        .HasColumnType("int");

                    b.HasKey("GamesId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("GameTag");
                });

            modelBuilder.Entity("WmBlazor.Shared.Developer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Developers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Colossal order are a game developer",
                            Name = "Colossal Order"
                        },
                        new
                        {
                            Id = 2,
                            Description = "System Era Softworks is a small development studio led by veteran game developers headquartered in Seattle, Washington. We are currently working on our first game, Astroneer.",
                            Name = "System Era Softworks"
                        },
                        new
                        {
                            Id = 3,
                            Description = "A world famous games developer",
                            Name = "BANDAI NAMCO Studios Inc."
                        },
                        new
                        {
                            Id = 4,
                            Description = "A games studio famous for their racing simulators",
                            Name = "Kunos Simulazioni"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Not as bad as EA",
                            Name = "Developer: HB Studios Multimedia Ltd. "
                        });
                });

            modelBuilder.Entity("WmBlazor.Shared.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeveloperId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PriceGb")
                        .HasColumnType("decimal(8,2)");

                    b.Property<int>("PublisherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperId");

                    b.HasIndex("PublisherId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A city-building game by Colossal Order",
                            DeveloperId = 1,
                            Name = "Cities Skylines",
                            PriceGb = 22.99m,
                            PublisherId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "A cute little space exploration game",
                            DeveloperId = 2,
                            Name = "Astroneer",
                            PriceGb = 23.79m,
                            PublisherId = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "A combat flight simulator by BANDAI NAMCO Studios Inc.",
                            DeveloperId = 3,
                            Name = "Ace Combat 7: Skies Unknown",
                            PriceGb = 49.99m,
                            PublisherId = 3
                        },
                        new
                        {
                            Id = 4,
                            Description = "A racing simulator by Kunos Simulazoni",
                            DeveloperId = 4,
                            Name = "Assetto Corsa Competizione",
                            PriceGb = 34.99m,
                            PublisherId = 4
                        },
                        new
                        {
                            Id = 5,
                            Description = "A golf simulator",
                            DeveloperId = 5,
                            Name = "PGA Tour 2K21",
                            PriceGb = 49.99m,
                            PublisherId = 5
                        });
                });

            modelBuilder.Entity("WmBlazor.Shared.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "We create the games. You create the stories.",
                            Name = "Paradox Interactive"
                        },
                        new
                        {
                            Id = 2,
                            Description = "System Era Softworks is a small development studio led by veteran game developers headquartered in Seattle, Washington. We are currently working on our first game, Astroneer.",
                            Name = "System Era Softworks"
                        },
                        new
                        {
                            Id = 3,
                            Description = "BANDAI NAMCO Entertainment, is a leading interactive entertainment software publisher known for creating and publishing many of the industry top video game franchises.",
                            Name = "BANDAI NAMCO Entertainment"
                        },
                        new
                        {
                            Id = 4,
                            Description = "505 Games is a global game publisher focused on offering a broad selection of titles for players of all ages and levels.",
                            Name = "505 Games"
                        },
                        new
                        {
                            Id = 5,
                            Description = "2K develops and publishes critically-acclaimed franchises such as BioShock, Borderlands, Sid Meier’s Civilization, XCOM, WWE 2K, and NBA 2K.",
                            Name = "2K"
                        });
                });

            modelBuilder.Entity("WmBlazor.Shared.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Member"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("WmBlazor.Shared.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Flight"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Jet"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Military"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "War"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "Shooter"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Name = "Arcade"
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            Name = "City Builder"
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            Name = "Simulation"
                        },
                        new
                        {
                            Id = 9,
                            IsActive = true,
                            Name = "Building"
                        },
                        new
                        {
                            Id = 10,
                            IsActive = true,
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 11,
                            IsActive = true,
                            Name = "Local Multiplayer"
                        },
                        new
                        {
                            Id = 12,
                            IsActive = true,
                            Name = "Multiplayer"
                        },
                        new
                        {
                            Id = 13,
                            IsActive = true,
                            Name = "Open World"
                        },
                        new
                        {
                            Id = 14,
                            IsActive = true,
                            Name = "Racing"
                        },
                        new
                        {
                            Id = 15,
                            IsActive = true,
                            Name = "Automobile Sim"
                        },
                        new
                        {
                            Id = 16,
                            IsActive = true,
                            Name = "VR"
                        },
                        new
                        {
                            Id = 17,
                            IsActive = true,
                            Name = "Golf"
                        });
                });

            modelBuilder.Entity("WmBlazor.Shared.User", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Username");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GameTag", b =>
                {
                    b.HasOne("WmBlazor.Shared.Game", null)
                        .WithMany()
                        .HasForeignKey("GamesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WmBlazor.Shared.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WmBlazor.Shared.Game", b =>
                {
                    b.HasOne("WmBlazor.Shared.Developer", "Developer")
                        .WithMany("Games")
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WmBlazor.Shared.Publisher", "Publisher")
                        .WithMany("Games")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Developer");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("WmBlazor.Shared.User", b =>
                {
                    b.HasOne("WmBlazor.Shared.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("WmBlazor.Shared.Developer", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("WmBlazor.Shared.Publisher", b =>
                {
                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
